spring.application.name=matching-guru
spring.datasource.url=jdbc:postgresql://localhost:5432/matching-guru
spring.datasource.username=postgres
spring.datasource.password=1029384756
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.liquibase.change-log=classpath:/db/baseChangelog.xml
jwt.secret=51U0E8SPdwRCTvNkj8Mk4Qx0dx6olE/xuxIw5j+7e82PNuNrX+mFdwAAWO+MoR4NNTPgcfOfnlYKUA8XNDtZ3A==
jwt.expiration=86400000

logging.level.uk.bovykina.matching_guru.algorithms=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=DEBUG
#server.error.include-message=always
#server.error.include-binding-errors=always

cloudinary.cloud-name=docf6adny
cloudinary.api-key=733222639924663
cloudinary.api-secret=EBQ150TDeSRCiwXNYbsuyKxiBNg
