spring.application.name=matching-guru
#spring.datasource.url=jdbc:postgresql://localhost:5432/matching-guru
#spring.datasource.username=postgres
#spring.datasource.password=1029384756
spring.datasource.url=jdbc:postgresql://pg-1f05b196-paulina-64bc.k.aivencloud.com:22848/defaultdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_EbMhBkT37YuPvwDH5He
spring.datasource.driver-class-name=org.postgresql.Driver
# Connection Pooling (HikariCP)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000
# JPA & Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.liquibase.change-log=classpath:/db/baseChangelog.xml
jwt.secret=51U0E8SPdwRCTvNkj8Mk4Qx0dx6olE/xuxIw5j+7e82PNuNrX+mFdwAAWO+MoR4NNTPgcfOfnlYKUA8XNDtZ3A==
jwt.expiration=86400000
logging.level.uk.bovykina.matching_guru.algorithms=DEBUG
#logging.level.org.springframework.web=DEBUG
#logging.level.org.hibernate=DEBUG
#server.error.include-message=always
#server.error.include-binding-errors=always
cloudinary.cloud-name=docf6adny
cloudinary.api-key=733222639924663
cloudinary.api-secret=EBQ150TDeSRCiwXNYbsuyKxiBNg
server.port=8080
sendgrid.api-key=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
app.mail.from=21mafiozi21@gmail.com
app.mail.fromName="Matching Guru Notifications"
app.mail.template.welcome=welcome-email
app.mail.template.matchApproved=match-approved
app.mail.template.matchConfirmed=match
app.mail.template.feedbackRequest=feedback
