package uk.bovykina.matching_guru.entity.enums;

public enum Skill {
    COMMUNICATION,
    LEADERSHIP,
    PROBLEM_SOLVING,
    TIME_MANAGEMENT,
    TEAMWORK,
    CRITICAL_THINKING,
    ADAPTABILITY,
    NETWORKING,
    PROGRAMMING,
    ANALYTICAL_SKILLS,
    PROJECT_MANAGEMENT,
    FINANCIAL_LITERACY,
    WRITING_AND_RESEARCH,
    MARKETING,
    DESIGN,
    FOREIGN_LANGUAGES,
    STATISTICS,
    ENGINEERING,
    EXAM_PREPARATION,
    NOTE_TAKING,
    ENTERPRENEURSHIP,
    LABORATORY_TECHNIQUES
}
